# -*- coding: utf-8 -*-
"""Assignment16_corrected (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cII38HJMuF3gZsMGGrt8ZzB9NzuPD1RR

# Assignment 16 — LoRA Fine-Tuning of DistilGPT2

**Task:** Load a small GPT model (DistilGPT2), apply LoRA using the PEFT library, and fine-tune it on a text dataset. Compare the model before and after fine-tuning (trainable parameters, training time, sample generated text), and discuss the advantages of LoRA over full fine-tuning in terms of memory usage, computational cost, and performance.

**Dataset:** `Abirate/english_quotes` (English quotes for causal language modeling)

## 1. Environment Setup
"""

# Remove conflicting packages
!pip uninstall -y torchao transformers peft accelerate datasets -q

# Install compatible versions
!pip install -q \
transformers==4.51.3 \
peft==0.15.2 \
accelerate==1.5.2 \
datasets==2.21.0

import os

print("Restarting runtime...")
os.kill(os.getpid(), 9)

import torch
import time

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)

from datasets import load_dataset

from peft import (
    LoraConfig,
    get_peft_model,
    TaskType
)

import torch
import transformers
import peft
import accelerate
import datasets

print("Torch:", torch.__version__)
print("Transformers:", transformers.__version__)
print("PEFT:", peft.__version__)
print("Accelerate:", accelerate.__version__)
print("Datasets:", datasets.__version__)

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

if device == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))

"""## 2. Load Baseline Model & Tokenizer"""

model_name = "distilgpt2"

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForCausalLM.from_pretrained(model_name)

model.to(device)

tokenizer.pad_token = tokenizer.eos_token
model.config.pad_token_id = tokenizer.eos_token_id

# --- Memory footprint of the FULL model on GPU, before any LoRA wrapping ---
# This number is the basis for the memory-usage discussion at the end of the notebook.
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()
    base_model_memory_mb = torch.cuda.memory_allocated() / (1024 ** 2)
    print(f"GPU memory used by base model weights: {base_model_memory_mb:.2f} MB")
else:
    base_model_memory_mb = None
    print("CUDA not available — memory profiling skipped (run on a GPU runtime for real numbers).")

"""### Parameter count before LoRA
Before any LoRA adapters are added, **every** parameter of DistilGPT2 is trainable — this is the "full fine-tuning" reference point we compare against.
"""

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(
    p.numel() for p in model.parameters()
    if p.requires_grad
)

print("="*40)
print("Before LoRA")
print("="*40)
print(f"Total Parameters      : {total_params:,}")
print(f"Trainable Parameters  : {trainable_params:,}")

"""## 3. Load & Tokenize Dataset"""

dataset = load_dataset("Abirate/english_quotes")
dataset

dataset = dataset["train"]

dataset = dataset.remove_columns(["author", "tags"])

dataset

max_length = 64

def tokenize(batch):
    return tokenizer(
        batch["quote"],
        truncation=True,
        padding="max_length",
        max_length=max_length
    )

tokenized_dataset = dataset.map(
    tokenize,
    batched=True
)

tokenized_dataset

tokenized_dataset = tokenized_dataset.remove_columns(["quote"])

tokenized_dataset.set_format("torch")

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

"""## 4. Apply LoRA
LoRA is injected only into the attention projection layer (`c_attn`, which holds the fused Q/K/V weights in GPT-2-style models). The base weights are frozen; only the small low-rank matrices are trainable.
"""

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["c_attn"]
)

model = get_peft_model(model, lora_config)

model.print_trainable_parameters()

# --- Memory footprint right after wrapping the model with LoRA (adapters added, still on GPU) ---
if torch.cuda.is_available():
    lora_model_memory_mb = torch.cuda.memory_allocated() / (1024 ** 2)
    print(f"GPU memory used after adding LoRA adapters: {lora_model_memory_mb:.2f} MB")
    print(f"Extra memory added by LoRA adapters: {lora_model_memory_mb - base_model_memory_mb:.2f} MB")
else:
    lora_model_memory_mb = None
    print("CUDA not available — memory profiling skipped.")

"""## 5. Training"""

training_args = TrainingArguments(
    output_dir="./lora_distilgpt2",

    overwrite_output_dir=True,

    num_train_epochs=50,

    per_device_train_batch_size=8,

    save_strategy="no",

    logging_steps=50,

    learning_rate=2e-4,

    weight_decay=0.01,

    fp16=torch.cuda.is_available(),

    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset,
    data_collator=data_collator,
)

# Reset peak-memory tracking right before training so we can capture the true training-time peak
# (this is the number that matters for the memory-usage comparison, since it includes optimizer states
# and activations, not just the frozen model weights).
if torch.cuda.is_available():
    torch.cuda.reset_peak_memory_stats()

start_time = time.time()

trainer.train()

training_time = time.time() - start_time

print(f"Training Time : {training_time:.2f} seconds")

# --- Peak GPU memory actually used during LoRA training ---
if torch.cuda.is_available():
    peak_train_memory_mb = torch.cuda.max_memory_allocated() / (1024 ** 2)
    print(f"Peak GPU memory during LoRA fine-tuning: {peak_train_memory_mb:.2f} MB")
else:
    peak_train_memory_mb = None
    print("CUDA not available — memory profiling skipped.")

"""## 6. Text Generation — Quick Check After Training"""

def generate_text(model, prompt):

    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    output = model.generate(
        **inputs,
        max_new_tokens=50,
        do_sample=True,
        temperature=0.8,
        top_k=50,
        top_p=0.95,
        pad_token_id=tokenizer.eos_token_id
    )

    return tokenizer.decode(output[0], skip_special_tokens=True)

prompt = "Success is"

generated = generate_text(model, prompt)

print(generated)

model.save_pretrained("lora_distilgpt2")

tokenizer.save_pretrained("lora_distilgpt2")

"""## 7. Parameter Comparison"""

before_trainable = total_params

after_trainable = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print("="*50)
print("Parameter Comparison")
print("="*50)

print(f"Before LoRA Trainable : {before_trainable:,}")

print(f"After LoRA Trainable  : {after_trainable:,}")

print(f"Reduction             : {(1-after_trainable/before_trainable)*100:.2f}%")

print("="*60)
print("Assignment Summary")
print("="*60)

print(f"Model               : DistilGPT2")
print(f"Dataset             : English Quotes")
print(f"Training Epochs     : 10")
print(f"Training Time       : {training_time:.2f} sec")
print(f"Trainable Params    : {after_trainable:,}")

"""## 8. Before vs. After Fine-Tuning — Side-by-Side Generation
To get a fair "before" sample, a **fresh, untouched copy** of DistilGPT2 is reloaded from the hub (the `model` variable was mutated in-place into the LoRA model in Section 4, so it can no longer represent the baseline).
"""

from transformers import AutoTokenizer, AutoModelForCausalLM

original_model = AutoModelForCausalLM.from_pretrained("distilgpt2")
original_model.to(device)
original_model.eval()

original_tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
original_tokenizer.pad_token = original_tokenizer.eos_token

def generate_text(model, tokenizer, prompt):

    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=60,
            do_sample=True,
            temperature=0.8,
            top_p=0.95,
            top_k=50,
            pad_token_id=tokenizer.eos_token_id
        )

    return tokenizer.decode(outputs[0], skip_special_tokens=True)

prompt = "Success is"

before_text = generate_text(
    original_model,
    original_tokenizer,
    prompt
)

print("===== BEFORE FINE-TUNING =====\n")
print(before_text)

model.eval()

after_text = generate_text(
    model,
    tokenizer,
    prompt
)

print("===== AFTER FINE-TUNING =====\n")
print(after_text)

print("="*80)
print("MODEL COMPARISON")
print("="*80)

print("\nPrompt:\n")
print(prompt)

print("\n")
print("-"*80)
print("Before Fine-Tuning")
print("-"*80)

print(before_text)

print("\n")
print("-"*80)
print("After Fine-Tuning")
print("-"*80)

print(after_text)

"""## 9. Final Parameter, Time & Memory Summary"""

print("="*60)
print("PARAMETER COMPARISON")
print("="*60)

print(f"Total Parameters          : {total_params:,}")

print(f"Before LoRA Trainable     : {total_params:,}")

after_trainable = sum(
    p.numel()
    for p in model.parameters()
    if p.requires_grad
)

print(f"After LoRA Trainable      : {after_trainable:,}")

print(f"Training Time             : {training_time:.2f} seconds")

print(f"Percentage Trainable      : {(after_trainable/total_params)*100:.4f}%")

print("="*60)
print("MEMORY COMPARISON (GPU, empirical)")
print("="*60)
if torch.cuda.is_available():
    print(f"Base model weights only        : {base_model_memory_mb:.2f} MB")
    print(f"Model + LoRA adapters (idle)   : {lora_model_memory_mb:.2f} MB")
    print(f"Peak memory during LoRA training: {peak_train_memory_mb:.2f} MB")
    # Rough theoretical estimate of what full fine-tuning would need for optimizer states alone
    # (Adam keeps 2 extra fp32 buffers per trainable parameter: momentum + variance)
    full_ft_optimizer_mb = (total_params * 2 * 4) / (1024 ** 2)
    lora_optimizer_mb = (after_trainable * 2 * 4) / (1024 ** 2)
    print(f"\nEstimated Adam optimizer-state memory:")
    print(f"  Full fine-tuning (all {total_params:,} params) : {full_ft_optimizer_mb:.2f} MB")
    print(f"  LoRA fine-tuning ({after_trainable:,} params)      : {lora_optimizer_mb:.2f} MB")
else:
    print("Run this notebook on a GPU runtime to populate empirical memory figures.")

results = {
    "Model": "DistilGPT2 + LoRA",
    "Dataset": "Abirate/english_quotes",
    "Total Parameters": total_params,
    "Trainable Parameters": after_trainable,
    "Training Time (sec)": round(training_time, 2),
    "Before Text": before_text,
    "After Text": after_text
}

for key, value in results.items():
    print(f"\n{key}:\n{value}")

"""## 10. Discussion — LoRA vs. Full Fine-Tuning

**Trainable parameters.** Full fine-tuning of DistilGPT2 updates all **81,912,576** parameters. With LoRA restricted to the `c_attn` projections (r=8, alpha=16), only **147,456** parameters are trainable — about **0.18%** of the full model. This is the single biggest lever LoRA pulls: it re-parameterizes the weight *update* as a low-rank decomposition (ΔW = BA, with B and A far smaller than W) instead of learning a full-rank update for every weight matrix.

**Memory usage.** Because the base weights stay frozen, LoRA never needs gradients or optimizer state for ~99.8% of the parameters. For Adam specifically, the optimizer keeps two extra fp32 buffers (momentum and variance) per *trainable* parameter — so full fine-tuning must budget optimizer memory for all 81.9M parameters, while LoRA only needs it for the ~147K adapter parameters (see the empirical and estimated figures printed above). In practice this is what lets LoRA fine-tune models that wouldn't otherwise fit in GPU memory at all, or lets a given GPU handle a much larger batch size / longer sequence length for the same memory budget.

**Computational cost.** Backpropagation cost scales with the number of parameters that need gradients computed and stored. With the base model frozen, LoRA still runs a full forward pass through the original network (so forward-pass cost is roughly unchanged), but the backward pass only needs to compute gradients for the tiny adapter matrices, and the optimizer step only touches those same ~147K values. This reduces backward-pass compute and optimizer-step overhead considerably, and — since checkpoints only need to store the adapter weights (a few hundred KB–MB vs. hundreds of MB for the full model) — it also makes saving, sharing, and swapping fine-tuned "skills" much cheaper.

**Performance / quality.** On this run, generation shifted noticeably after training: the base DistilGPT2 continuation for "Success is" was generic ("*Success is now available.*"), while the LoRA fine-tuned model produced longer, more aphorism-like continuations that echo the style of the `english_quotes` training data. This matches the general finding in the LoRA literature: for lightweight adaptation tasks (style transfer, domain adaptation, instruction tuning of small/medium models), LoRA typically recovers most of the quality gain of full fine-tuning at a fraction of the trainable-parameter and memory cost, though full fine-tuning can still have an edge when the target task requires large, distributed changes to the model's underlying representations rather than a localized adjustment.

**Summary table**

| Aspect | Full Fine-Tuning | LoRA Fine-Tuning |
|---|---|---|
| Trainable parameters | 81,912,576 (100%) | 147,456 (~0.18%) |
| Optimizer memory (Adam, fp32 states) | Scales with all 81.9M params | Scales with ~147K params only |
| Checkpoint size | Full model (~hundreds of MB) | Adapter only (~KB–low MB) |
| Backward-pass / optimizer-step cost | Full | Greatly reduced |
| Risk of catastrophic forgetting | Higher (all weights move) | Lower (base weights frozen) |
| Typical quality vs. full FT | Reference / upper bound | Close, for lightweight adaptation tasks |

"""